@startuml
class Member
class BoardMember
class Event
class Conference
class BoardMeeting
class Location
class Person
class AAUOC
Event <|-- Conference
Event <|-- BoardMeeting
Member <|-- BoardMember
Person <|-- Member
AAUOC o-- Person
AAUOC o-- "0..*" Event
AAUOC o--"0..*" Location
Event "0..*" --"1" Location : isLocated In
Event "0..*"-- "0..*" Member : attendsTo
BoardMember"0..*" -- "0..*" BoardMeeting:attendsTo
Conference "0..*" -- "0..*" Person:attendsTo



@enduml




